import vue from './languages/vue'
const hljs = require('highlight.js/lib/core')

hljs.registerLanguage('xml', require('highlight.js/lib/languages/xml'))
// hljs.registerLanguage('apache', require('highlight.js/lib/languages/apache'))
hljs.registerLanguage('bash', require('highlight.js/lib/languages/bash'))
// hljs.registerLanguage('c-like', require('highlight.js/lib/languages/c-like'))
// hljs.registerLanguage('c', require('highlight.js/lib/languages/c'))
hljs.registerLanguage('cpp', require('highlight.js/lib/languages/cpp'))
hljs.registerLanguage('css', require('highlight.js/lib/languages/css'))
// hljs.registerLanguage('dart', require('highlight.js/lib/languages/dart'))
hljs.registerLanguage('markdown', require('highlight.js/lib/languages/markdown'))
hljs.registerLanguage('diff', require('highlight.js/lib/languages/diff'))
// hljs.registerLanguage('dockerfile', require('highlight.js/lib/languages/dockerfile'))
// hljs.registerLanguage('go', require('highlight.js/lib/languages/go'))
hljs.registerLanguage('htmlbars', require('highlight.js/lib/languages/htmlbars'))
// hljs.registerLanguage('http', require('highlight.js/lib/languages/http'))
hljs.registerLanguage('ini', require('highlight.js/lib/languages/ini'))
hljs.registerLanguage('java', require('highlight.js/lib/languages/java'))
hljs.registerLanguage('javascript', require('highlight.js/lib/languages/javascript'))
hljs.registerLanguage('json', require('highlight.js/lib/languages/json'))
hljs.registerLanguage('less', require('highlight.js/lib/languages/less'))
// hljs.registerLanguage('makefile', require('highlight.js/lib/languages/makefile'))
hljs.registerLanguage('nginx', require('highlight.js/lib/languages/nginx'))
hljs.registerLanguage('pgsql', require('highlight.js/lib/languages/pgsql'))
// hljs.registerLanguage('php', require('highlight.js/lib/languages/php'))
// hljs.registerLanguage('php-template', require('highlight.js/lib/languages/php-template'))
hljs.registerLanguage('powershell', require('highlight.js/lib/languages/powershell'))
hljs.registerLanguage('python', require('highlight.js/lib/languages/python'))
hljs.registerLanguage('scss', require('highlight.js/lib/languages/scss'))
hljs.registerLanguage('shell', require('highlight.js/lib/languages/shell'))
hljs.registerLanguage('sql_more', require('highlight.js/lib/languages/sql_more'))
hljs.registerLanguage('sql', require('highlight.js/lib/languages/sql'))
// hljs.registerLanguage('yaml', require('highlight.js/lib/languages/yaml'))
hljs.registerLanguage('typescript', require('highlight.js/lib/languages/typescript'))

hljs.registerLanguage('vue', vue)

export default hljs
